
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
