@echo off
echo Starting .NET Core server...
start cmd /k "cd server && dotnet ef database update && dotnet run"

echo Starting React client...
start cmd /k "cd client && npm install && npm start"

echo Server and client are starting...
